language: android

# default tools/target is 25, use 28 instead:
android:
  components:
  - build-tools-28.0.3
  - android-28

script:
- ./gradlew build jacocoTestReport check

after_success:
- bash <(curl -s https://codecov.io/bash)