language: android

# default tools/target is 25, use 28 instead:
android:
  components:
  - build-tools-28.0.3
  - android-28

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- ./gradlew build check

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
- bash <(curl -s https://codecov.io/bash)